### ISSUE TITLE
[CP 2007]  No Item

### ISSUE THREAD

**Issue by IMRaccoon** [KUSVV-2021/SMA_Project#152]
29 : [CP 2007]  No Item
http://3.35.83.31:8090/testrail/index.php?/cases/view/29

**Comment by com8599** [comment]
![삭제 테스트](https://user-images.githubusercontent.com/13133477/118957296-5dd14f80-b99b-11eb-9432-40c376504cce.png)
해당 프로세스로 재시도 부탁드립니다.

**Comment by lji9605** [comment]
![image](https://user-images.githubusercontent.com/47684593/118966318-94f82e80-b9a4-11eb-9b51-97e050852a0f.png)

문서를 기반으로 보시면 어느 부분에서도 재고가 0이 된다는 말이 없을 뿐더러 당연히 상품을 삭제한다고 하면 해당 제품이 DVM 안에서 사라지는게 삭제된다는 표현이지 재고가 0으로 되는 것이 삭제가 된다는 표현과는 맞지 않다고 생각합니다.
DB에서 stock이 0으로 update되는 것이 아닌 해당 제품이 delete되는 것이 맞는 기능이라고 생각합니다.

**Comment by com8599** [comment]
저도 그게 맞다 생각하여 팀원들에게 고지했으나, 팀원들은 해당 기기의 재고삭제만 하는것이라고 하였습니다. 삭제부탁드립니다.

**Comment by com8599** [comment]
해당부분 다시 회의후 코멘트 새로 달겠습니다.
