### ISSUE TITLE
[CP 2008] Remove Item

### ISSUE THREAD

**Issue by IMRaccoon** [KUSVV-2021/SMA_Project#153]
30 : [CP 2008] Remove Item
http://3.35.83.31:8090/testrail/index.php?/cases/view/30

**Comment by com8599** [comment]
![삭제 테스트](https://user-images.githubusercontent.com/13133477/118957296-5dd14f80-b99b-11eb-9432-40c376504cce.png)
해당 프로세스로 재시도 부탁드립니다.

**Comment by lji9605** [comment]
2007번과 동일합니다.
개발에 관한 모든 사항들은 사전에 문서로 정의가 되어있어야 합니다.
문서를 기반으로 테스트를 진행하는 저희 입장에서는 문서에 없는 사항들은 다 issue 처리될 수 밖에 없습니다.
