### ISSUE TITLE
[STA 4018] Avoid Static Import

### ISSUE THREAD

**Issue by IMRaccoon** [KUSVV-2021/SMA_Project#290]
http://13.209.162.187:9000/project/issues?id=SMA_Project&resolved=false&rules=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.AvoidStaticImportCheck

해결방안: import 문에 static 을 삭제

**Comment by com8599** [comment]
이슈가 보이지않습니다 close 부탁드립니다.
